[build]
  publish = "."
  functions = "functions"

[functions."check-signals"]
  schedule = "*/5 * * * *"

[functions."check-fxfutures"]
  schedule = "*/5 * * * *"

[functions."check-news"]
  schedule = "*/30 * * * *"

[functions."check-sportsbet"]
  schedule = "0 10 * * *"
